---


- name: install packages
  apt:
    pkg: '{{ item }}'
    update_cache: yes
    cache_valid_time: 3600
    install_recommends: no
  with_items:
    - git
    - python-yaml
    - python-jinja2

- name: clone cw-ansible git sources
  git:
    repo: '{{ item.repo }}'
    dest: '{{ item.dest }}'
    clone: '{{ item.clone | default(True) }}'
    version: '{{ item.version | default("HEAD") }}'
  when: ansible_bootstrap_cw_repository is defined
  with_items: ansible_bootstrap_cw_repository
  sudo_user: ansible

- name: bootstrap cw-ansible
  command:
    ./scripts/bootstrap-linux
  args:
    chdir: '{{ ansible_bootstrap_home_directory }}/cw-ansible'
    creates: '{{ ansible_bootstrap_home_directory }}/cw-ansible/playbooks/inventory.example'
