---


- include: user-osx.yml
  when: ansible_system == 'Darwin'

- include: user-linux.yml
  when: ansible_system == 'Linux'

- name: Copy ansible ssh public key
  authorized_key:
    user: '{{ansible_bootstrap_user_name}}'
    key: '{{ansible_bootstrap_ssh_key}}'
    manage_dir: no
  when: ansible_bootstrap_ssh_key is defined
  
- include: deploy-ansible.yml
  when:
    ansible_bootstrap_deploy_ansible is defined
    and ansible_bootstrap_deploy_ansible
