---

- name: install required packages
  apt:
    pkg: {{item}}
    update_cache: yes
    install_recommends: no
    cache_valid_time: 3600
    force: yes
  with_items:
    - python-apt
    - sudo
    - lsb-release
