# Before bootstraping ansible user on OpenBSD you should be able to log into
# system as root without password (you must install your public ssh key into
# root account).
#
# ssh-copy-id  -o IdentitiesOnly=yes root@host.example.com
#
# Copy your SSH key into .ssh/authorized_keys
#
# Then install pyhton:
#
# export PKG_PATH=http://ftp2.fr.openbsd.org/pub/OpenBSD/`uname -r`/packages/`machine -a`/
# pkg_info -Q python
# pkg_add python-2.7.9p0
# ln -sf /usr/local/bin/python2.7 /usr/bin/python
#

# you don't need other python links


# ln -sf /usr/local/bin/python2.7 /usr/local/bin/python
# ln -sf /usr/local/bin/python2.7-2to3 /usr/local/bin/2to3
# ln -sf /usr/local/bin/python2.7-config /usr/local/bin/python-config
# ln -sf /usr/local/bin/pydoc2.7  /usr/local/bin/pydoc


---

- name: OpenBSD - Create ansible group
  group:
    name: '{{ item.name | default(ansible_bootstrap_group_name) }}'
    gid: '{{ item.gid | default(ansible_bootstrap_ansible_gid) }}'
    state: '{{ item.state | default("present") }}'
    system: '{{ item.system | default(True) }}'
  with_items: ansible_bootstrap_group

  
- name: OpenBSD - create ansible user
  user:
    name: '{{ item.name | default(ansible_bootstrap_user_name) }}'
    comment: '{{ item.comment | default("Ansible configuration agent") }}'
    system: '{{ item.system | default(True) }}'
    home: '{{ item.home | default(ansible_bootstrap_home_directory) }}'
    group: '{{ item.name | default(ansible_bootstrap_user_name) }}'
    #groups: '{{ item.groups | default(None) }}'
    uid: '{{ item.uid | default(ansible_bootstrap_ansible_uid) }}'
    state: '{{ item.state | default("present") }}'
    createhome: '{{ item.createhome | default(True) }}'
  with_items: ansible_bootstrap_user


- name: OpenBSD - make sure .ansible/tmp exists in ansible home
  file:
    path='{{ansible_bootstrap_home_directory}}/{{item.path}}'
    mode='{{ item.mode|default("0700") }}'
    owner='{{ansible_bootstrap_user_name}}'
    group='{{ansible_bootstrap_user_name}}'
    state=directory
  with_items:
    - { path: .ssh }
    - { path: .ansible }
    - { path: .ansible/tmp }
  
#- include: packages-apt.yml
- include: sudo-single.yml
